// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void notif_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Task_Page
void ui_Task_Page_screen_init(void);
void ui_event_Task_Page( lv_event_t * e);
lv_obj_t *ui_Task_Page;
lv_obj_t *ui_topTask;
lv_obj_t *ui_curse;
lv_obj_t *ui_centerTask;
lv_obj_t *ui_bottomTask;
void ui_event_UpButton( lv_event_t * e);
lv_obj_t *ui_UpButton;
lv_obj_t *ui_UPButton;
lv_obj_t *ui_downButton;
lv_obj_t *ui_downB;
void ui_event_homeFromTask( lv_event_t * e);
lv_obj_t *ui_homeFromTask;
lv_obj_t *ui_downB2;
// CUSTOM VARIABLES


// SCREEN: ui_Focus_Page
void ui_Focus_Page_screen_init(void);
void ui_event_Focus_Page( lv_event_t * e);
lv_obj_t *ui_Focus_Page;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_clock;
lv_obj_t *ui_title_for_page;
lv_obj_t *ui_Label2;
void ui_event_homeFromFocus( lv_event_t * e);
lv_obj_t *ui_homeFromFocus;
lv_obj_t *ui_Label7;
// CUSTOM VARIABLES


// SCREEN: ui_Home_Page
void ui_Home_Page_screen_init(void);
lv_obj_t *ui_Home_Page;
lv_obj_t *ui_Label1;
void ui_event_taskFromHome( lv_event_t * e);
lv_obj_t *ui_taskFromHome;
lv_obj_t *ui_Label9;
void ui_event_focusFromHome( lv_event_t * e);
lv_obj_t *ui_focusFromHome;
lv_obj_t *ui_Label10;
lv_obj_t *ui_nextTask;
lv_obj_t *ui_nextTasklabel;
void ui_event_currentTask( lv_event_t * e);
lv_obj_t *ui_currentTask;
lv_obj_t *ui_currentTaskLable;
lv_obj_t *ui_Container1;
lv_obj_t *ui_time;
lv_obj_t *ui_selectedTask;
void ui_event_topButton( lv_event_t * e);
lv_obj_t *ui_topButton;
lv_obj_t *ui_skip;
void ui_event_bottomButton( lv_event_t * e);
lv_obj_t *ui_bottomButton;
void ui_event_back( lv_event_t * e);
lv_obj_t *ui_back;
void ui_event_selectButton( lv_event_t * e);
lv_obj_t *ui_selectButton;
void ui_event_done( lv_event_t * e);
lv_obj_t *ui_done;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void notif_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 0);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Task_Page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Focus_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Focus_Page_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_UpButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_topTask, target, "asdfghjkl", "lkjhgfdsa");
}
}

void ui_event_homeFromTask( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_Focus_Page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_homeFromFocus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_taskFromHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Task_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Task_Page_screen_init);
}
}

void ui_event_focusFromHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Focus_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Focus_Page_screen_init);
}
}

void ui_event_currentTask( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Container1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_topButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Container1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_currentTaskLable, target, "Next task", "next next task");
}
}

void ui_event_bottomButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Container1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_back( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_selectButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Container1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_currentTaskLable, target, "first task", "secon task");
}
}

void ui_event_done( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Task_Page_screen_init();
ui_Focus_Page_screen_init();
ui_Home_Page_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Task_Page);
}
