// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Task_Page
void ui_Task_Page_screen_init(void);
void ui_event_Task_Page( lv_event_t * e);
lv_obj_t *ui_Task_Page;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_topTask;
lv_obj_t *ui_bottomTask;
void ui_event_curseBox( lv_event_t * e);
lv_obj_t *ui_curseBox;
lv_obj_t *ui_centerTask;
void ui_event_UpButton( lv_event_t * e);
lv_obj_t *ui_UpButton;
lv_obj_t *ui_UPButton;
lv_obj_t *ui_downButton;
lv_obj_t *ui_downB;
void ui_event_homeFromTask( lv_event_t * e);
lv_obj_t *ui_homeFromTask;
lv_obj_t *ui_downB2;
lv_obj_t *ui_taskPageLabel;
lv_obj_t *ui_taskInfo;
lv_obj_t *ui_timeOfTask;
lv_obj_t *ui_selectedTask1;
lv_obj_t *ui_skippedData;
lv_obj_t *ui_completedData;
void ui_event_closeTaskInfo( lv_event_t * e);
lv_obj_t *ui_closeTaskInfo;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_skipped;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_completed;
// CUSTOM VARIABLES


// SCREEN: ui_Focus_Page
void ui_Focus_Page_screen_init(void);
void ui_event_Focus_Page( lv_event_t * e);
lv_obj_t *ui_Focus_Page;
lv_obj_t *ui_clock;
lv_obj_t *ui_focusPageLabel;
lv_obj_t *ui_actualTask;
void ui_event_homeFromFocus( lv_event_t * e);
lv_obj_t *ui_homeFromFocus;
lv_obj_t *ui_homeButtonFromFocus;
lv_obj_t *ui_decor3;
lv_obj_t *ui_decor4;
// CUSTOM VARIABLES


// SCREEN: ui_Home_Page
void ui_Home_Page_screen_init(void);
lv_obj_t *ui_Home_Page;
lv_obj_t *ui_homePageLabel;
void ui_event_taskFromHome( lv_event_t * e);
lv_obj_t *ui_taskFromHome;
lv_obj_t *ui_taskButtonFromHome;
void ui_event_focusFromHome( lv_event_t * e);
lv_obj_t *ui_focusFromHome;
lv_obj_t *ui_focusButtonFromHome;
lv_obj_t *ui_nextTask;
lv_obj_t *ui_nextTasklabel;
void ui_event_currentTask( lv_event_t * e);
lv_obj_t *ui_currentTask;
lv_obj_t *ui_currentTaskLable;
lv_obj_t *ui_Container1;
lv_obj_t *ui_time;
lv_obj_t *ui_selectedTask;
void ui_event_topButton( lv_event_t * e);
lv_obj_t *ui_topButton;
lv_obj_t *ui_skip;
void ui_event_bottomButton( lv_event_t * e);
lv_obj_t *ui_bottomButton;
void ui_event_done( lv_event_t * e);
lv_obj_t *ui_done;
void ui_event_selectButton( lv_event_t * e);
lv_obj_t *ui_selectButton;
void ui_event_back( lv_event_t * e);
lv_obj_t *ui_back;
lv_obj_t *ui_decor1;
lv_obj_t *ui_decor2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Task_Page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Focus_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Focus_Page_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_curseBox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_taskInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_UpButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_topTask, target, "asdfghjkl", "lkjhgfdsa");
}
}

void ui_event_homeFromTask( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_closeTaskInfo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_taskInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_Focus_Page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_homeFromFocus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_taskFromHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Task_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Task_Page_screen_init);
}
}

void ui_event_focusFromHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Focus_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Focus_Page_screen_init);
}
}

void ui_event_currentTask( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Container1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_topButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Container1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_currentTaskLable, target, "jafsdsd", "Next Taskgjskdjfdd");
}
}

void ui_event_bottomButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Container1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_done( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_selectButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_Container1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_currentTaskLable, target, "first task", "secon task");
}
}

void ui_event_back( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Task_Page_screen_init();
ui_Focus_Page_screen_init();
ui_Home_Page_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Task_Page);
}
