// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void notif_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Task_Page
void ui_Task_Page_screen_init(void);
void ui_event_Task_Page( lv_event_t * e);
extern lv_obj_t *ui_Task_Page;
extern lv_obj_t *ui_topTask;
void ui_event_curseBox( lv_event_t * e);
extern lv_obj_t *ui_curseBox;
extern lv_obj_t *ui_centerTask;
extern lv_obj_t *ui_bottomTask;
void ui_event_UpButton( lv_event_t * e);
extern lv_obj_t *ui_UpButton;
extern lv_obj_t *ui_UPButton;
extern lv_obj_t *ui_downButton;
extern lv_obj_t *ui_downB;
void ui_event_homeFromTask( lv_event_t * e);
extern lv_obj_t *ui_homeFromTask;
extern lv_obj_t *ui_downB2;
extern lv_obj_t *ui_taskPageLabel;
extern lv_obj_t *ui_taskInfo;
extern lv_obj_t *ui_timeOfTask;
extern lv_obj_t *ui_selectedTask1;
extern lv_obj_t *ui_skippedData;
extern lv_obj_t *ui_completedData;
void ui_event_closeTaskInfo( lv_event_t * e);
extern lv_obj_t *ui_closeTaskInfo;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_skipped;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_completed;
// CUSTOM VARIABLES

// SCREEN: ui_Focus_Page
void ui_Focus_Page_screen_init(void);
void ui_event_Focus_Page( lv_event_t * e);
extern lv_obj_t *ui_Focus_Page;
extern lv_obj_t *ui_clock;
extern lv_obj_t *ui_focusPageLabel;
extern lv_obj_t *ui_actualTask;
void ui_event_homeFromFocus( lv_event_t * e);
extern lv_obj_t *ui_homeFromFocus;
extern lv_obj_t *ui_homeButtonFromFocus;
// CUSTOM VARIABLES

// SCREEN: ui_Home_Page
void ui_Home_Page_screen_init(void);
extern lv_obj_t *ui_Home_Page;
extern lv_obj_t *ui_homePageLabel;
void ui_event_taskFromHome( lv_event_t * e);
extern lv_obj_t *ui_taskFromHome;
extern lv_obj_t *ui_taskButtonFromHome;
void ui_event_focusFromHome( lv_event_t * e);
extern lv_obj_t *ui_focusFromHome;
extern lv_obj_t *ui_focusButtonFromHome;
extern lv_obj_t *ui_nextTask;
extern lv_obj_t *ui_nextTasklabel;
void ui_event_currentTask( lv_event_t * e);
extern lv_obj_t *ui_currentTask;
extern lv_obj_t *ui_currentTaskLable;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_time;
extern lv_obj_t *ui_selectedTask;
void ui_event_topButton( lv_event_t * e);
extern lv_obj_t *ui_topButton;
extern lv_obj_t *ui_skip;
void ui_event_bottomButton( lv_event_t * e);
extern lv_obj_t *ui_bottomButton;
void ui_event_done( lv_event_t * e);
extern lv_obj_t *ui_done;
void ui_event_selectButton( lv_event_t * e);
extern lv_obj_t *ui_selectButton;
void ui_event_back( lv_event_t * e);
extern lv_obj_t *ui_back;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
