// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Focus_Page_screen_init(void)
{
ui_Focus_Page = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Focus_Page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Focus_Page, lv_color_hex(0xCBECD3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Focus_Page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabView1 = lv_tabview_create(ui_Focus_Page, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView1, 274);
lv_obj_set_height( ui_TabView1, 130);
lv_obj_set_x( ui_TabView1, -11 );
lv_obj_set_y( ui_TabView1, -2 );
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x9CBAC2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_clock = lv_label_create(ui_Focus_Page);
lv_obj_set_width( ui_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock, -7 );
lv_obj_set_y( ui_clock, -39 );
lv_obj_set_align( ui_clock, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock,"12:36 PM");
lv_obj_set_style_text_font(ui_clock, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_title_for_page = lv_label_create(ui_Focus_Page);
lv_obj_set_width( ui_title_for_page, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_title_for_page, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_title_for_page, -124 );
lv_obj_set_y( ui_title_for_page, -96 );
lv_obj_set_align( ui_title_for_page, LV_ALIGN_CENTER );
lv_label_set_text(ui_title_for_page,"Focus Page!");
lv_obj_set_style_text_font(ui_title_for_page, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Focus_Page);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, 27 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"LOCK INNNN :)");

ui_homeFromFocus = lv_btn_create(ui_Focus_Page);
lv_obj_set_width( ui_homeFromFocus, 61);
lv_obj_set_height( ui_homeFromFocus, 17);
lv_obj_set_x( ui_homeFromFocus, 197 );
lv_obj_set_y( ui_homeFromFocus, 3 );
lv_obj_set_align( ui_homeFromFocus, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_homeFromFocus, lv_color_hex(0x080707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_homeFromFocus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_homeFromFocus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_homeFromFocus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_homeFromFocus);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -1 );
lv_obj_set_y( ui_Label7, 0 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Home");

lv_obj_add_event_cb(ui_homeFromFocus, ui_event_homeFromFocus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Focus_Page, ui_event_Focus_Page, LV_EVENT_ALL, NULL);

}
