// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Home_Page_screen_init(void)
{
ui_Home_Page = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home_Page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Home_Page, lv_color_hex(0x758173), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Home_Page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Home_Page);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -131 );
lv_obj_set_y( ui_Label1, -109 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"HOME PAGE ;)");

ui_taskFromHome = lv_btn_create(ui_Home_Page);
lv_obj_set_width( ui_taskFromHome, 61);
lv_obj_set_height( ui_taskFromHome, 17);
lv_obj_set_x( ui_taskFromHome, 203 );
lv_obj_set_y( ui_taskFromHome, 0 );
lv_obj_set_align( ui_taskFromHome, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_taskFromHome, lv_color_hex(0x080707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_taskFromHome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_taskFromHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_taskFromHome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_taskFromHome);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -1 );
lv_obj_set_y( ui_Label9, 0 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"TASKS");

ui_focusFromHome = lv_btn_create(ui_Home_Page);
lv_obj_set_width( ui_focusFromHome, 61);
lv_obj_set_height( ui_focusFromHome, 17);
lv_obj_set_x( ui_focusFromHome, -202 );
lv_obj_set_y( ui_focusFromHome, 0 );
lv_obj_set_align( ui_focusFromHome, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_focusFromHome, lv_color_hex(0x080707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_focusFromHome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_focusFromHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_focusFromHome, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_focusFromHome);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -1 );
lv_obj_set_y( ui_Label10, 0 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"FOCUS");

ui_nextTask = lv_obj_create(ui_Home_Page);
lv_obj_set_width( ui_nextTask, 184);
lv_obj_set_height( ui_nextTask, 50);
lv_obj_set_x( ui_nextTask, 3 );
lv_obj_set_y( ui_nextTask, 73 );
lv_obj_set_align( ui_nextTask, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_nextTask, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_nextTasklabel = lv_label_create(ui_nextTask);
lv_obj_set_width( ui_nextTasklabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_nextTasklabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_nextTasklabel, 1 );
lv_obj_set_y( ui_nextTasklabel, 1 );
lv_obj_set_align( ui_nextTasklabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_nextTasklabel,"Next Task");

ui_currentTask = lv_obj_create(ui_Home_Page);
lv_obj_set_width( ui_currentTask, 250);
lv_obj_set_height( ui_currentTask, 69);
lv_obj_set_x( ui_currentTask, 6 );
lv_obj_set_y( ui_currentTask, -12 );
lv_obj_set_align( ui_currentTask, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_currentTask, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_currentTaskLable = lv_label_create(ui_currentTask);
lv_obj_set_width( ui_currentTaskLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentTaskLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentTaskLable, 1 );
lv_obj_set_y( ui_currentTaskLable, 1 );
lv_obj_set_align( ui_currentTaskLable, LV_ALIGN_CENTER );
lv_label_set_text(ui_currentTaskLable,"Current Task");

ui_Container1 = lv_obj_create(ui_Home_Page);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 296);
lv_obj_set_height( ui_Container1, 207);
lv_obj_set_x( ui_Container1, 3 );
lv_obj_set_y( ui_Container1, -8 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Container1, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_Container1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time = lv_label_create(ui_Container1);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time, 10 );
lv_obj_set_y( ui_time, 17 );
lv_obj_set_align( ui_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_time,"11:00 PM");

ui_selectedTask = lv_label_create(ui_Container1);
lv_obj_set_width( ui_selectedTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectedTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectedTask, 5 );
lv_obj_set_y( ui_selectedTask, -35 );
lv_obj_set_align( ui_selectedTask, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectedTask,"\"Selected Task\"");

ui_topButton = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_topButton, 75);
lv_obj_set_height( ui_topButton, 24);
lv_obj_set_x( ui_topButton, -109 );
lv_obj_set_y( ui_topButton, 42 );
lv_obj_set_align( ui_topButton, LV_ALIGN_CENTER );

ui_skip = lv_label_create(ui_topButton);
lv_obj_set_width( ui_skip, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_skip, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_skip, LV_ALIGN_CENTER );
lv_label_set_text(ui_skip,"Skip");

ui_bottomButton = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_bottomButton, 73);
lv_obj_set_height( ui_bottomButton, 22);
lv_obj_set_x( ui_bottomButton, -110 );
lv_obj_set_y( ui_bottomButton, 84 );
lv_obj_set_align( ui_bottomButton, LV_ALIGN_CENTER );

ui_back = lv_label_create(ui_bottomButton);
lv_obj_set_width( ui_back, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_back, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_back, LV_ALIGN_CENTER );
lv_label_set_text(ui_back,"Back");

ui_selectButton = lv_btn_create(ui_Container1);
lv_obj_set_width( ui_selectButton, 73);
lv_obj_set_height( ui_selectButton, 22);
lv_obj_set_x( ui_selectButton, 101 );
lv_obj_set_y( ui_selectButton, 78 );
lv_obj_set_align( ui_selectButton, LV_ALIGN_CENTER );

ui_done = lv_label_create(ui_selectButton);
lv_obj_set_width( ui_done, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_done, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_done, LV_ALIGN_CENTER );
lv_label_set_text(ui_done,"Done");

lv_obj_add_event_cb(ui_taskFromHome, ui_event_taskFromHome, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_focusFromHome, ui_event_focusFromHome, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_currentTask, ui_event_currentTask, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_topButton, ui_event_topButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_back, ui_event_back, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bottomButton, ui_event_bottomButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_done, ui_event_done, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectButton, ui_event_selectButton, LV_EVENT_ALL, NULL);

}
