// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Task_Page_screen_init(void)
{
ui_Task_Page = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Task_Page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Task_Page, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Task_Page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Task_Page);
lv_obj_set_width( ui_Panel3, 355);
lv_obj_set_height( ui_Panel3, 150);
lv_obj_set_x( ui_Panel3, 40 );
lv_obj_set_y( ui_Panel3, 0 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_topTask = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_topTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_topTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_topTask, 0 );
lv_obj_set_y( ui_topTask, -5 );
lv_label_set_text(ui_topTask,"topTask");
lv_obj_set_style_text_color(ui_topTask, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_topTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_topTask, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bottomTask = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_bottomTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bottomTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bottomTask, 0 );
lv_obj_set_y( ui_bottomTask, 5 );
lv_obj_set_align( ui_bottomTask, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_bottomTask,"bottomTask");
lv_obj_set_style_text_color(ui_bottomTask, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bottomTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bottomTask, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_curseBox = lv_obj_create(ui_Task_Page);
lv_obj_set_width( ui_curseBox, 355);
lv_obj_set_height( ui_curseBox, 69);
lv_obj_set_x( ui_curseBox, 40 );
lv_obj_set_y( ui_curseBox, -2 );
lv_obj_set_align( ui_curseBox, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_curseBox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_curseBox, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_curseBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_centerTask = lv_label_create(ui_curseBox);
lv_obj_set_width( ui_centerTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_centerTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_centerTask, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_centerTask,"centerTask");
lv_obj_set_style_text_color(ui_centerTask, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_centerTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_centerTask, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UpButton = lv_btn_create(ui_Task_Page);
lv_obj_set_width( ui_UpButton, 65);
lv_obj_set_height( ui_UpButton, 20);
lv_obj_set_x( ui_UpButton, 0 );
lv_obj_set_y( ui_UpButton, -140 );
lv_obj_set_align( ui_UpButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_UpButton, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_UpButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_UpButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_UpButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UPButton = lv_label_create(ui_UpButton);
lv_obj_set_width( ui_UPButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UPButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UPButton, -1 );
lv_obj_set_y( ui_UPButton, 0 );
lv_obj_set_align( ui_UPButton, LV_ALIGN_CENTER );
lv_label_set_text(ui_UPButton,"UP");

ui_downButton = lv_btn_create(ui_Task_Page);
lv_obj_set_width( ui_downButton, 65);
lv_obj_set_height( ui_downButton, 20);
lv_obj_set_x( ui_downButton, 0 );
lv_obj_set_y( ui_downButton, 140 );
lv_obj_set_align( ui_downButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_downButton, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_downButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_downButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_downButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_downB = lv_label_create(ui_downButton);
lv_obj_set_width( ui_downB, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_downB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_downB, -1 );
lv_obj_set_y( ui_downB, 0 );
lv_obj_set_align( ui_downB, LV_ALIGN_CENTER );
lv_label_set_text(ui_downB,"DOWN");

ui_homeFromTask = lv_btn_create(ui_Task_Page);
lv_obj_set_width( ui_homeFromTask, 65);
lv_obj_set_height( ui_homeFromTask, 20);
lv_obj_set_x( ui_homeFromTask, -203 );
lv_obj_set_y( ui_homeFromTask, 0 );
lv_obj_set_align( ui_homeFromTask, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_homeFromTask, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_homeFromTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_homeFromTask, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_homeFromTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_downB2 = lv_label_create(ui_homeFromTask);
lv_obj_set_width( ui_downB2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_downB2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_downB2, -1 );
lv_obj_set_y( ui_downB2, 0 );
lv_obj_set_align( ui_downB2, LV_ALIGN_CENTER );
lv_label_set_text(ui_downB2,"HOME");

ui_taskPageLabel = lv_label_create(ui_Task_Page);
lv_obj_set_width( ui_taskPageLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_taskPageLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_taskPageLabel, 184 );
lv_obj_set_y( ui_taskPageLabel, 148 );
lv_obj_set_align( ui_taskPageLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_taskPageLabel,"TASK PAGE <3");
lv_obj_set_style_text_color(ui_taskPageLabel, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_taskPageLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_taskPageLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_taskInfo = lv_obj_create(ui_Task_Page);
lv_obj_remove_style_all(ui_taskInfo);
lv_obj_set_width( ui_taskInfo, 363);
lv_obj_set_height( ui_taskInfo, 214);
lv_obj_set_x( ui_taskInfo, 25 );
lv_obj_set_y( ui_taskInfo, 0 );
lv_obj_set_align( ui_taskInfo, LV_ALIGN_CENTER );
lv_obj_add_state( ui_taskInfo, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_taskInfo, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_clear_flag( ui_taskInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_taskInfo, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_taskInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_taskInfo, lv_color_hex(0x3C3737), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_taskInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_taskInfo, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_taskInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_taskInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_taskInfo, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_taskInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeOfTask = lv_label_create(ui_taskInfo);
lv_obj_set_width( ui_timeOfTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeOfTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeOfTask, 107 );
lv_obj_set_y( ui_timeOfTask, -75 );
lv_obj_set_align( ui_timeOfTask, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeOfTask,"11:00 PM");
lv_obj_set_style_text_color(ui_timeOfTask, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeOfTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectedTask1 = lv_label_create(ui_taskInfo);
lv_obj_set_width( ui_selectedTask1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectedTask1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectedTask1, -88 );
lv_obj_set_y( ui_selectedTask1, -75 );
lv_obj_set_align( ui_selectedTask1, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectedTask1,"\"Selected Task\"");
lv_obj_set_style_text_color(ui_selectedTask1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectedTask1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectedTask1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_skippedData = lv_label_create(ui_taskInfo);
lv_obj_set_width( ui_skippedData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_skippedData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_skippedData, 65 );
lv_obj_set_y( ui_skippedData, 0 );
lv_obj_set_align( ui_skippedData, LV_ALIGN_CENTER );
lv_label_set_text(ui_skippedData,"skippedData");
lv_obj_set_style_text_color(ui_skippedData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_skippedData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_completedData = lv_label_create(ui_taskInfo);
lv_obj_set_width( ui_completedData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_completedData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_completedData, 65 );
lv_obj_set_y( ui_completedData, 45 );
lv_obj_set_align( ui_completedData, LV_ALIGN_CENTER );
lv_label_set_text(ui_completedData,"completedData");
lv_obj_set_style_text_color(ui_completedData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_completedData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_closeTaskInfo = lv_btn_create(ui_taskInfo);
lv_obj_set_width( ui_closeTaskInfo, 70);
lv_obj_set_height( ui_closeTaskInfo, 20);
lv_obj_set_x( ui_closeTaskInfo, 120 );
lv_obj_set_y( ui_closeTaskInfo, 82 );
lv_obj_set_align( ui_closeTaskInfo, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_closeTaskInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_closeTaskInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_closeTaskInfo, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_closeTaskInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_closeTaskInfo);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Back");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_taskInfo);
lv_obj_set_width( ui_Panel1, 155);
lv_obj_set_height( ui_Panel1, 20);
lv_obj_set_x( ui_Panel1, -80 );
lv_obj_set_y( ui_Panel1, 0 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_skipped = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_skipped, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_skipped, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_skipped, LV_ALIGN_CENTER );
lv_label_set_text(ui_skipped,"Skipped Amount:");
lv_obj_set_style_text_color(ui_skipped, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_skipped, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_taskInfo);
lv_obj_set_width( ui_Panel2, 155);
lv_obj_set_height( ui_Panel2, 20);
lv_obj_set_x( ui_Panel2, -80 );
lv_obj_set_y( ui_Panel2, 46 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_completed = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_completed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_completed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_completed, LV_ALIGN_CENTER );
lv_label_set_text(ui_completed,"Completed Amount:");
lv_obj_set_style_text_color(ui_completed, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_completed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_completed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_curseBox, ui_event_curseBox, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_UpButton, ui_event_UpButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_homeFromTask, ui_event_homeFromTask, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_closeTaskInfo, ui_event_closeTaskInfo, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Task_Page, ui_event_Task_Page, LV_EVENT_ALL, NULL);

}
