// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Task_Page_screen_init(void)
{
ui_Task_Page = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Task_Page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Task_Page, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Task_Page, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_topTask = lv_label_create(ui_Task_Page);
lv_obj_set_width( ui_topTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_topTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_topTask, 0 );
lv_obj_set_y( ui_topTask, -55 );
lv_obj_set_align( ui_topTask, LV_ALIGN_CENTER );
lv_label_set_text(ui_topTask,"topTask");
lv_obj_set_style_text_color(ui_topTask, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_topTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_topTask, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_curseBox = lv_obj_create(ui_Task_Page);
lv_obj_set_width( ui_curseBox, 250);
lv_obj_set_height( ui_curseBox, 69);
lv_obj_set_align( ui_curseBox, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_curseBox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_curseBox, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_curseBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_centerTask = lv_label_create(ui_Task_Page);
lv_obj_set_width( ui_centerTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_centerTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_centerTask, LV_ALIGN_CENTER );
lv_label_set_text(ui_centerTask,"centerTask");
lv_obj_set_style_text_color(ui_centerTask, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_centerTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_centerTask, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bottomTask = lv_label_create(ui_Task_Page);
lv_obj_set_width( ui_bottomTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bottomTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bottomTask, 0 );
lv_obj_set_y( ui_bottomTask, 55 );
lv_obj_set_align( ui_bottomTask, LV_ALIGN_CENTER );
lv_label_set_text(ui_bottomTask,"bottomTask");
lv_obj_set_style_text_color(ui_bottomTask, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_bottomTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bottomTask, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UpButton = lv_btn_create(ui_Task_Page);
lv_obj_set_width( ui_UpButton, 65);
lv_obj_set_height( ui_UpButton, 20);
lv_obj_set_x( ui_UpButton, 0 );
lv_obj_set_y( ui_UpButton, -140 );
lv_obj_set_align( ui_UpButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_UpButton, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_UpButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_UpButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_UpButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UPButton = lv_label_create(ui_UpButton);
lv_obj_set_width( ui_UPButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UPButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UPButton, -1 );
lv_obj_set_y( ui_UPButton, 0 );
lv_obj_set_align( ui_UPButton, LV_ALIGN_CENTER );
lv_label_set_text(ui_UPButton,"UP");

ui_downButton = lv_btn_create(ui_Task_Page);
lv_obj_set_width( ui_downButton, 65);
lv_obj_set_height( ui_downButton, 20);
lv_obj_set_x( ui_downButton, 0 );
lv_obj_set_y( ui_downButton, 140 );
lv_obj_set_align( ui_downButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_downButton, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_downButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_downButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_downButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_downB = lv_label_create(ui_downButton);
lv_obj_set_width( ui_downB, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_downB, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_downB, -1 );
lv_obj_set_y( ui_downB, 0 );
lv_obj_set_align( ui_downB, LV_ALIGN_CENTER );
lv_label_set_text(ui_downB,"DOWN");

ui_homeFromTask = lv_btn_create(ui_Task_Page);
lv_obj_set_width( ui_homeFromTask, 65);
lv_obj_set_height( ui_homeFromTask, 20);
lv_obj_set_x( ui_homeFromTask, -203 );
lv_obj_set_y( ui_homeFromTask, 0 );
lv_obj_set_align( ui_homeFromTask, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_homeFromTask, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_homeFromTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_homeFromTask, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_homeFromTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_downB2 = lv_label_create(ui_homeFromTask);
lv_obj_set_width( ui_downB2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_downB2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_downB2, -1 );
lv_obj_set_y( ui_downB2, 0 );
lv_obj_set_align( ui_downB2, LV_ALIGN_CENTER );
lv_label_set_text(ui_downB2,"HOME");

ui_Label2 = lv_label_create(ui_Task_Page);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 187 );
lv_obj_set_y( ui_Label2, 148 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"TASK PAGE <3");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_notification = lv_obj_create(ui_Task_Page);
lv_obj_remove_style_all(ui_notification);
lv_obj_set_width( ui_notification, 330);
lv_obj_set_height( ui_notification, 214);
lv_obj_set_x( ui_notification, 1 );
lv_obj_set_y( ui_notification, 1 );
lv_obj_set_align( ui_notification, LV_ALIGN_CENTER );
lv_obj_add_state( ui_notification, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( ui_notification, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_clear_flag( ui_notification, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_notification, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_notification, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_notification, lv_color_hex(0x3C3737), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_notification, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_notification, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_notification, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_notification, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_notification, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_notification, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time1 = lv_label_create(ui_notification);
lv_obj_set_width( ui_time1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time1, -70 );
lv_obj_set_y( ui_time1, 25 );
lv_obj_set_align( ui_time1, LV_ALIGN_CENTER );
lv_label_set_text(ui_time1,"11:00 PM");
lv_obj_set_style_text_color(ui_time1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_time1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectedTask1 = lv_label_create(ui_notification);
lv_obj_set_width( ui_selectedTask1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectedTask1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectedTask1, -70 );
lv_obj_set_y( ui_selectedTask1, -15 );
lv_obj_set_align( ui_selectedTask1, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectedTask1,"\"Selected Task\"");
lv_obj_set_style_text_color(ui_selectedTask1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectedTask1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectedTask1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_topButton1 = lv_btn_create(ui_notification);
lv_obj_set_width( ui_topButton1, 65);
lv_obj_set_height( ui_topButton1, 20);
lv_obj_set_x( ui_topButton1, 65 );
lv_obj_set_y( ui_topButton1, 22 );
lv_obj_set_align( ui_topButton1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_topButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_topButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_skip1 = lv_label_create(ui_topButton1);
lv_obj_set_width( ui_skip1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_skip1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_skip1, LV_ALIGN_CENTER );
lv_label_set_text(ui_skip1,"Skip");
lv_obj_set_style_text_color(ui_skip1, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_skip1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_skip1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bottomButton1 = lv_btn_create(ui_notification);
lv_obj_set_width( ui_bottomButton1, 65);
lv_obj_set_height( ui_bottomButton1, 20);
lv_obj_set_x( ui_bottomButton1, 66 );
lv_obj_set_y( ui_bottomButton1, 84 );
lv_obj_set_align( ui_bottomButton1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_bottomButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bottomButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_done1 = lv_label_create(ui_bottomButton1);
lv_obj_set_width( ui_done1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_done1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_done1, LV_ALIGN_CENTER );
lv_label_set_text(ui_done1,"Done");
lv_obj_set_style_text_color(ui_done1, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_done1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_done1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectButton1 = lv_btn_create(ui_notification);
lv_obj_set_width( ui_selectButton1, 65);
lv_obj_set_height( ui_selectButton1, 20);
lv_obj_set_x( ui_selectButton1, 120 );
lv_obj_set_y( ui_selectButton1, 50 );
lv_obj_set_align( ui_selectButton1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_selectButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_selectButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_back1 = lv_label_create(ui_selectButton1);
lv_obj_set_width( ui_back1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_back1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_back1, LV_ALIGN_CENTER );
lv_label_set_text(ui_back1,"Back");
lv_obj_set_style_text_color(ui_back1, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_back1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_back1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_curseBox, ui_event_curseBox, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_UpButton, ui_event_UpButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_homeFromTask, ui_event_homeFromTask, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_topButton1, ui_event_topButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_done1, ui_event_done1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bottomButton1, ui_event_bottomButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_back1, ui_event_back1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectButton1, ui_event_selectButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Task_Page, ui_event_Task_Page, LV_EVENT_ALL, NULL);

}
