// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONTAINER1_H
#define _UI_COMP_CONTAINER1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Container1
#define UI_COMP_CONTAINER1_CONTAINER1 0
#define UI_COMP_CONTAINER1_TIME 1
#define UI_COMP_CONTAINER1_SELECTEDTASK 2
#define UI_COMP_CONTAINER1_TOPBUTTON 3
#define UI_COMP_CONTAINER1_TOPBUTTON_SKIP 4
#define UI_COMP_CONTAINER1_BOTTOMBUTTON 5
#define UI_COMP_CONTAINER1_BOTTOMBUTTON_BACK 6
#define UI_COMP_CONTAINER1_SELECTBUTTON 7
#define UI_COMP_CONTAINER1_SELECTBUTTON_DONE 8
#define _UI_COMP_CONTAINER1_NUM 9
lv_obj_t *ui_Container1_create(lv_obj_t *comp_parent);
void ui_event_comp_Container1_topButton( lv_event_t * e);
void ui_event_comp_Container1_bottomButton( lv_event_t * e);
void ui_event_comp_Container1_back( lv_event_t * e);
void ui_event_comp_Container1_selectButton( lv_event_t * e);
void ui_event_comp_Container1_done( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
