// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


void ui_event_comp_Container1_topButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_Container1 = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( comp_Container1[UI_COMP_CONTAINER1_CONTAINER1], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_currentTaskLable, target, "jafsdsd", "Next Taskgjskdjfdd");
}
}

void ui_event_comp_Container1_bottomButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_Container1 = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( comp_Container1[UI_COMP_CONTAINER1_CONTAINER1], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_comp_Container1_back( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_Container1 = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_comp_Container1_selectButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_Container1 = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( comp_Container1[UI_COMP_CONTAINER1_CONTAINER1], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_checked_set_text_value( ui_currentTaskLable, target, "first task", "secon task");
}
}

void ui_event_comp_Container1_done( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_Container1 = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_Page_screen_init);
}
}

// COMPONENT Container1

lv_obj_t *ui_Container1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Container1;
cui_Container1 = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_Container1);
lv_obj_set_width( cui_Container1, 296);
lv_obj_set_height( cui_Container1, 207);
lv_obj_set_x( cui_Container1, 3 );
lv_obj_set_y( cui_Container1, -8 );
lv_obj_set_align( cui_Container1, LV_ALIGN_CENTER );
lv_obj_add_state( cui_Container1, LV_STATE_DISABLED );     /// States
lv_obj_add_flag( cui_Container1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_clear_flag( cui_Container1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_Container1, lv_color_hex(0x0B0B0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_Container1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_time;
cui_time = lv_label_create(cui_Container1);
lv_obj_set_width( cui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_time, -59 );
lv_obj_set_y( cui_time, -17 );
lv_obj_set_align( cui_time, LV_ALIGN_CENTER );
lv_label_set_text(cui_time,"11:00 PM");
lv_obj_set_style_text_color(cui_time, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_selectedTask;
cui_selectedTask = lv_label_create(cui_Container1);
lv_obj_set_width( cui_selectedTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_selectedTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_selectedTask, -54 );
lv_obj_set_y( cui_selectedTask, -45 );
lv_obj_set_align( cui_selectedTask, LV_ALIGN_CENTER );
lv_label_set_text(cui_selectedTask,"\"Selected Task\"");
lv_obj_set_style_text_color(cui_selectedTask, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_selectedTask, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_selectedTask, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_topButton;
cui_topButton = lv_btn_create(cui_Container1);
lv_obj_set_width( cui_topButton, 75);
lv_obj_set_height( cui_topButton, 24);
lv_obj_set_x( cui_topButton, 49 );
lv_obj_set_y( cui_topButton, 19 );
lv_obj_set_align( cui_topButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(cui_topButton, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_topButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_skip;
cui_skip = lv_label_create(cui_topButton);
lv_obj_set_width( cui_skip, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_skip, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_skip, LV_ALIGN_CENTER );
lv_label_set_text(cui_skip,"Skip");

lv_obj_t *cui_bottomButton;
cui_bottomButton = lv_btn_create(cui_Container1);
lv_obj_set_width( cui_bottomButton, 73);
lv_obj_set_height( cui_bottomButton, 22);
lv_obj_set_x( cui_bottomButton, 53 );
lv_obj_set_y( cui_bottomButton, 85 );
lv_obj_set_align( cui_bottomButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(cui_bottomButton, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_bottomButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_back;
cui_back = lv_label_create(cui_bottomButton);
lv_obj_set_width( cui_back, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_back, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_back, LV_ALIGN_CENTER );
lv_label_set_text(cui_back,"Back");

lv_obj_t *cui_selectButton;
cui_selectButton = lv_btn_create(cui_Container1);
lv_obj_set_width( cui_selectButton, 73);
lv_obj_set_height( cui_selectButton, 22);
lv_obj_set_x( cui_selectButton, 103 );
lv_obj_set_y( cui_selectButton, 50 );
lv_obj_set_align( cui_selectButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(cui_selectButton, lv_color_hex(0x003049), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_selectButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_done;
cui_done = lv_label_create(cui_selectButton);
lv_obj_set_width( cui_done, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_done, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_done, LV_ALIGN_CENTER );
lv_label_set_text(cui_done,"Done");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER1_NUM);
children[UI_COMP_CONTAINER1_CONTAINER1] = cui_Container1;
children[UI_COMP_CONTAINER1_TIME] = cui_time;
children[UI_COMP_CONTAINER1_SELECTEDTASK] = cui_selectedTask;
children[UI_COMP_CONTAINER1_TOPBUTTON] = cui_topButton;
children[UI_COMP_CONTAINER1_TOPBUTTON_SKIP] = cui_skip;
children[UI_COMP_CONTAINER1_BOTTOMBUTTON] = cui_bottomButton;
children[UI_COMP_CONTAINER1_BOTTOMBUTTON_BACK] = cui_back;
children[UI_COMP_CONTAINER1_SELECTBUTTON] = cui_selectButton;
children[UI_COMP_CONTAINER1_SELECTBUTTON_DONE] = cui_done;
lv_obj_add_event_cb(cui_Container1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Container1, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_topButton, ui_event_comp_Container1_topButton, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_back, ui_event_comp_Container1_back, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_bottomButton, ui_event_comp_Container1_bottomButton, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_done, ui_event_comp_Container1_done, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_selectButton, ui_event_comp_Container1_selectButton, LV_EVENT_ALL, children);
ui_comp_Container1_create_hook(cui_Container1);
return cui_Container1; 
}

