// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/raconnn.png
   const char *ui_img_raconnn_png = "S:assets/raconnn.png";
