// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Focus_Page_screen_init(void)
{
ui_Focus_Page = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Focus_Page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Focus_Page, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Pink);
ui_object_set_themeable_style_property(ui_Focus_Page, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Pink);

ui_clock = lv_label_create(ui_Focus_Page);
lv_obj_set_width( ui_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock, 72 );
lv_obj_set_y( ui_clock, -2 );
lv_obj_set_align( ui_clock, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock,"12:36 PM");
lv_obj_set_style_text_font(ui_clock, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_title_for_page = lv_label_create(ui_Focus_Page);
lv_obj_set_width( ui_title_for_page, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_title_for_page, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_title_for_page, -65 );
lv_obj_set_y( ui_title_for_page, -58 );
lv_obj_set_align( ui_title_for_page, LV_ALIGN_CENTER );
lv_label_set_text(ui_title_for_page,"Focus Page!\n");
lv_obj_set_style_text_font(ui_title_for_page, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);


}
