// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/dark.png
   const char *ui_img_dark_png = "S:assets/dark.png";
