// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/grey_cat.png
   const char *ui_img_grey_cat_png = "S:assets/grey_cat.png";
